// TypeScript compilation

// This file is generated by the tsd task
/// <reference path="../target/typings/tsd.d.ts" />

/// <reference path="src/setup/Application.ts" />

//grunt-start
/// <reference path="src/GlobalState.ts" />
/// <reference path="src/HelloWorldController.ts" />
/// <reference path="src/RootController.ts" />
//grunt-end

/// <reference path="src/setup/Bootstrap.ts" />
